### ISSUE TITLE
400 Bad Request Error with gpt-4-vision-preview on text2text_llm_chat_openai Actions

### ISSUE THREAD

**Issue by vtantia** [jetoslabs/autobots#124]
**Issue Summary**:

Encountering a `400 Bad Request` error when attempting to use `gpt-4-vision-preview` with the `text2text_llm_chat_openai` action type. It seems that the `gpt-4-vision-preview` model does not support some of the optional parameters available in the standard `gpt-4` model, such as `logprobs`, `logit_bias`, `response_format`, `tool_choice`, `tools`, and `top_logprobs`.

**Steps to Reproduce**:

1. Configure an action with the type `text2text_llm_chat_openai` to use the `gpt-4-vision-preview` model.
2. Execute the action.

**Expected Behavior**:

The action should complete successfully.

**Actual Behavior**:

The action fails with a `400 Bad Request` error. The error message suggests that certain fields are not permitted:

```
HTTP/1.1 400 Bad Request
{
"error": {
"message": "6 validation errors for Request
body -> logit_bias
extra fields not permitted (type=value_error.extra)
body -> logprobs
extra fields not permitted (type=value_error.extra)
body -> response_format
extra fields not permitted (type=value_error.extra)
body -> tool_choice
extra fields not permitted (type=value_error.extra)
body -> tools
extra fields not permitted (type=value_error.extra)
body -> top_logprobs
extra fields not permitted (type=value_error.extra)",
"type": "invalid_request_error"
}
}
```

**Logs**:

```
2024-02-02 01:27:34,481: INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions
```

**Comment by anuragjha** [comment]
done
